### ISSUE TITLE
voltron with jupyter notebook

### ISSUE THREAD

**Issue by smc9477** [BIMSBbioinfo/VoltRon#144]
Thank you for creating such a great tool.
I am trying to perform an analysis on a Jupyter Notebook using a conda environment as the kernel on a Linux server. However, the IP I can use is fixed, and it seems that the registerSpatialData function does not allow me to fix the IP. Additionally, due to server policies, I am unable to use RStudio.

Could you please suggest what I can do in this situation?

**Comment by Artur-man** [comment]
Hello there, 

Hmm perhaps I can configure the port where it can be an option for any function that requires shiny applications. As an alternative, if you wanna use VoltRon in a jupyter notebook (with R kernel?) perhaps we can trigger shiny using `htmlwidgets` which is supported in Jupyter notebooks. Could also be an alternative ?

**Comment by Artur-man** [comment]
I have pushed an update to the shiny-based routines to recognise `options` from [shinyApp](https://www.rdocumentation.org/packages/shiny/versions/1.9.1/topics/shinyApp) function. Hence now you can pass information on `host` and `port`. Wanna give it a try?

```
annotateSpatialData(visium_data, shiny.options = list(host = "127.0.0.1", port = 6356))

vrSpatialPlot(visium_data, interactive = TRUE, shiny.options = list(port = 6356))

annotateSpatialData(visium_data, shiny.options = list(port = 6356))

registerSpatialData(reference_spatdata = visium_data, 
                    query_spatdata = visium_data, 
                    shiny.options = list(host = "127.0.0.1", port = 6356))
```

The update is on [dev](https://github.com/BIMSBbioinfo/VoltRon/tree/dev) now. Please remove the R package, restart R session and download VoltRon from dev branch again to try.

**Comment by smc9477** [comment]
thank you for update function.

i've removed the R package and re-download from dev, but still there is no shiny.options at registerSpatialData function.
could you chek it? Thank you for your time

**Comment by Artur-man** [comment]
Hello there, I have just tried pulling from the dev branch to see if it is working, and it does: 
`devtools::install_github("BIMSBbioinfo/VoltRon@dev")`

Reinstalling R packages are bit more tricky and it should be, you have to make sure that you deleted it by attemping to delete twice, and restart the R session before downloading, otherwise you get the same package ... also `main` branch still doesnt have the moditification

**Comment by smc9477** [comment]
it worked successfully!! thank you so much for your effort!! 
i reinstalled R package with deleting three times (<- it really worked)
i had been working with fuji, but it's much better. 
![그림1](https://github.com/user-attachments/assets/f86a7aca-70c7-4243-8204-c4a46c9179e9)

**Comment by Artur-man** [comment]
It was my pleasure my friend, thanks for the feedback :D 
Just one question though, is this automated registration or manual ?

**Comment by smc9477** [comment]
Yes i used automated registration!

**Comment by Artur-man** [comment]
Hmm, we were thinking of implementing this as once you enter the correct parameters the run should just go through the alignment itself. We can implement this soon, will let know.

**Comment by Artur-man** [comment]
Hey there, we have an implementation for this now on the [main](https://github.com/BIMSBbioinfo/VoltRon) branch. See also [here](https://github.com/BIMSBbioinfo/VoltRon/issues/176). 

There are some examples in the [tutorials page](https://bioinformatics.mdc-berlin.de/VoltRon/registration.html#Automated_Image_Alignment) now too.
