### ISSUE TITLE
Installation Opencv path

### ISSUE THREAD

**Issue by dksenthil** [BIMSBbioinfo/VoltRon#173]
Installing package into ‘/home/skailasam/R/x86_64-pc-linux-gnu-library/4.4’
(as ‘lib’ is unspecified)
* installing *source* package ‘VoltRon’ ...
** using staged installation
This is pkg-config 1.8.1
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-I/usr/include/opencv4  -D_DATA_PREFIX=/usr
Using PKG_LIBS=-lopencv_stitching -lopencv_alphamat -lopencv_aruco -lopencv_barcode -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_cvv -lopencv_dnn_objdetect -lopencv_dnn_superres -lopencv_dpm -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_hfs -lopencv_img_hash -lopencv_intensity_transform -lopencv_line_descriptor -lopencv_mcc -lopencv_quality -lopencv_rapid -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_shape -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_optflow -lopencv_surface_matching -lopencv_tracking -lopencv_highgui -lopencv_datasets -lopencv_text -lopencv_plot -lopencv_ml -lopencv_videostab -lopencv_videoio -lopencv_viz -lopencv_wechat_qrcode -lopencv_ximgproc -lopencv_video -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_dnn -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core 
Found C++17 compiler: g++
Module <opencv2/xfeatures2d.hpp> has not been found on your system
Make sure to have an opencv4 library installed with the module available
ERROR: configuration failed for package ‘VoltRon’
* removing ‘/home/skailasam/R/x86_64-pc-linux-gnu-library/4.4/VoltRon’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpnHVykc/file1c55b352e3af/VoltRon_0.2.0.tar.gz’ had non-zero exit status.
  
  In Ubuntu 24.04 LTS. opencv gets install /usr/local. How to configure installation such that it recognizes the path for opencv

**Comment by Artur-man** [comment]
Added actions for `ubuntu-24.04` just to be sure, here https://github.com/Artur-man/VoltRon/commit/9f4a1d740c37dbf485dd937b5fea95a8f7af7875

**Comment by Artur-man** [comment]
R CMD check on `ubuntu-24.04` was implemented in https://github.com/Artur-man/VoltRon/commit/9f4a1d740c37dbf485dd937b5fea95a8f7af7875 and was successful. See here:
https://github.com/Artur-man/VoltRon/actions/runs/12496923097/job/34869111195

OpenCV was built as was shown at https://github.com/BIMSBbioinfo/VoltRon/blob/main/inst/extdata/install_ubuntu.md

**Comment by dksenthil** [comment]
Thanks 🙏 works fine in LTS 24 ..
