### ISSUE TITLE
Loading in a dataset in a custom format

### ISSUE THREAD

**Issue by pakiessling** [BIMSBbioinfo/VoltRon#82]
Hi again,

I am trying to load in our Merfish dataset and I am running into a few problems with `formVoltRon`.

I have 

- a dgTMatrix in gene x cell orientation
- a metadata data frame
- a coordinate data frame

I always get the error `"Entity IDs are not matching"` when I run

```
vr_object<- formVoltRon(data = matrix,
                        metadata = metadata,
                        coords = coordinates,
                        main.assay = "Merfish",
                        assay.type = "cell",
                        sample_name = "sample1")
```

All files have the same length and the same rownames.

Any ideas?

**Comment by Artur-man** [comment]
Hmm, that is unexpected my test data with coordinates, metadata and matrix performs well but I am currently testing other options. 

Will let you know ... meanwhile I made the following changes
* vrAssay objects to support both matrix and dgCMatrix 
* check for cases that coordinate data introduced as a data.frame rather than matrix

Artür

**Comment by Artur-man** [comment]
@pakiessling Perhaps it might also help me if I get a look at the formatting of the rownames and cell IDs. Can you do a `head()` on rownames (or colnames in gene x cell matrix) and post it here ?

**Comment by pakiessling** [comment]
I solved this problem by adding the rownames from the metadata to the matrix. Coming from python I was not used to that.

I now get the error:

```
Error in colSums(data): 'x' must be an array of at least two dimensions
Traceback:

1. formVoltRon(data = matrix, metadata = metadata, coords = coords, 
 .     main.assay = "Merfish", assay.type = "cell", sample_name = "sample1")
2. data.frame(Count = colSums(data), Assay = main.assay, Layer = layer_name, 
 .     Sample = sample_name, metadata, row.names = entityID)
3. colSums(data)
4. stop("'x' must be an array of at least two dimensions")
```

I guess something else must be wrong with my input. I have attached a brief describtion of my input:

**Matrix**
140 x 201268 sparse Matrix of class "dgTMatrix"

**Metadata**
A data.frame: 201268 × 22
X	fov	volume	min_x	min_y	max_x	max_y	anisotropy	transcript_count	perimeter_area_ratio	⋯	Cellbound2_high_pass	Cellbound3_raw	Cellbound3_high_pass	PolyT_raw	PolyT_high_pass	Cellbound1_raw	Cellbound1_high_pass	DAPI_raw	DAPI_high_pass	cell_type
<dbl>	<int>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<int>	<dbl>	⋯	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<chr>
1	2.474323e+18	48	1714.24077	2467.014	300.6891	2480.489	316.5513	1.266827	0	0.2988754	⋯	1555159.26	16626967	469538.75	176272358	6126009.9	33225611	916499.63	73886158	2329136.07	filtered
2	2.474323e+18	48	1762.67520	2503.471	302.2049	2518.096	317.3240	1.054288	0	0.2797901	⋯	900446.68	16915210	304941.07	185153474	3990056.9	34835348	608357.81	82507559	1563131.35	filtered
3	2.474323e+18	48	1976.83270	2558.867	316.0859	2574.034	331.9610	1.082086	0	0.2611537	⋯	962387.94	18765554	337786.76	213276317	3838761.2	38100296	654438.88	97759301	1723170.30	filtered
4	2.474323e+18	48	1579.21722	2469.822	319.7906	2483.100	335.1866	1.185120	0	0.2997098	⋯	791966.82	15304721	280371.14	193630934	4501508.9	31348314	549276.78	77591157	1527887.17	filtered

**Coords**
A data.frame: 201268 × 2
V2	V3
<dbl>	<dbl>
1	2473.192	309.20735
2	2511.161	309.81101
3	2566.364	324.13045
4	2476.590	327.90927
5	2478.058	356.84619

rownames(matrix) = 1:140 (just for testing)
colnames(matrix) = 1:1:201268
rownames(coords) = 1:201268
rownames(metadata) = 1:201268

**Comment by Artur-man** [comment]
Ah no worries :) thanks a lot for the feedback <3
